services:
  auth-lambda-app:
    image: gm50x/fiap-burger-auth-lambda
    build:
      context: .
    container_name: 'fiap-burger-auth-lambda'
    environment:
      NODE_ENV: 'development'
    env_file:
      - .env
    ports:
      - 30000:8080
